name: CI

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: macos-14
            target: aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - uses: graalvm/setup-graalvm@v1.2.2
        with:
          java-version: '22'
          distribution: 'liberica'
          set-java-home: 'true'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          working-directory: "bindings/extractous-python"
          args: --release --out dist --find-interpreter
          sccache: 'true'

      - name: Patch wheel lib
        run: |
          set -e
          python3 -m venv .venv
          source .venv/bin/activate
          pip install wheel
          bash .github/workflows/patch-wheel-lib-macos.sh bindings/extractous-python/dist

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.platform.target }}
          path: bindings/extractous-python/dist
      - name: pytest
        run: |
          set -e
          python3 -m venv .venv
          source .venv/bin/activate
          pip install extractous --find-links bindings/extractous-python/dist --force-reinstall
          pip install pytest scikit-learn
          cd bindings/extractous-python
          pytest -s
